spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:dgdg;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
      username: sa
  jpa:
    hibernate:
      ddl-auto: create
---
spring:
  config:
    activate:
      on-profile: local-pg
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${aws.secret-manager.url}
      username: ${aws.secret-manager.username}
      password: ${aws.secret-manager.password}
      maximum-pool-size: 10
      pool-name: local-pg-pool
  jpa:
    hibernate:
      ddl-auto: create
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${aws.secret-manager.url}
      username: ${aws.secret-manager.username}
      password: ${aws.secret-manager.password}
      maximum-pool-size: 30
      pool-name: dev-pg-pool

---
spring:
  config:
    activate:
      on-profile: real
